apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-data-pvc
  namespace: ${STACKGUARD_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STACKGUARD_STORAGE_CLASS}
  resources:
    requests:
      storage: ${SERVER_DATA_SIZE}
