apiVersion: v1
kind: Secret
metadata:
  name: stackguard-secrets
  namespace: ${STACKGUARD_NAMESPACE}
type: Opaque
stringData:
  STACKGUARD_SECRET: "${STACKGUARD_SECRET}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  STACKGUARD_DATABASE_URL: "${STACKGUARD_DATABASE_URL}"
