apiVersion: v1
kind: ConfigMap
metadata:
  name: stackguard-config
  namespace: {{ include "stackguard.namespace" . }}
  labels:
    {{- include "stackguard.labels" . | nindent 4 }}
data:
  STACKGUARD_DASHBOARD_URL: {{ .Values.urls.dashboard | quote }}
  STACKGUARD_API_URL: {{ .Values.urls.api | quote }}
  STACKGUARD_AI_URL: {{ .Values.urls.ai | quote }}
