{{- if .Values.vpa.enabled }}
{{- if .Values.dashboard.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: stackguard-dashboard-vpa
  namespace: {{ include "stackguard.namespace" . }}
  labels:
    {{- include "stackguard.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stackguard-dashboard
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
{{- end }}
---
{{- if .Values.server.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: stackguard-server-vpa
  namespace: {{ include "stackguard.namespace" . }}
  labels:
    {{- include "stackguard.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stackguard-server
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
{{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: stackguard-postgres-vpa
  namespace: {{ include "stackguard.namespace" . }}
  labels:
    {{- include "stackguard.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: stackguard-postgres
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
{{- end }}
{{- end }}
