apiVersion: v1
kind: Service
metadata:
  name: stackguard-postgres
  namespace: ${STACKGUARD_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: stackguard-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
